on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ðŸ”§ Setup repo
      uses: actions/checkout@v3

    - name: ðŸ”§ Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: ðŸ”§ Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: ðŸ”§ Setup Python
      uses: actions/setup-python@v2

    - name: ðŸ“¦ Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: ðŸ“¦ Install library dependencies
      run: pio lib -g install 1

    - name: ðŸš€ Run PlatformIO
      run: pio run